### PR TITLE
Add: text input history, use position: fixed for toolbar

### LINKED ISSUE #17: Save the "history" of filename pattern
https://addons.mozilla.org/zh-tw/firefox/addon/image-picka/reviews/985705/

We need some kind of editable select for this.

### PR DESCRIPTION
**Pull request by eight04**
Fixes #17.

### CODE REVIEW

File: lib/pref.js [hunk 1]
```diff
@@ -91,18 +112,62 @@ var pref = function(){
...
+			});
+			el.title = t;
+			return el;
+		}));
+		input.parentNode.append(list);
+		list.addEventListener("mousedown", () => {
+			list.classList.add("pending-click");
+			document.addEventListener("click", function onClick() {
+				list.remove();
+				document.removeEventListener("click", onClick);
```
Comment (eight04) [inline lib/pref.js]: Refactor `onFocusIn/onFocusOut` into `setupHistory` as a component.

File: picker/picker.css [hunk 2]
```diff
@@ -51,10 +57,12 @@
 .toolbar > * + * {
 	margin-left: 1em;
 }
-.toolbar label > * {
+.toolbar label > *,
+.toolbar-control > * {
 	margin: 0.7em 0;
 }
-.toolbar label > * + * {
+.toolbar label > * + *,
```
Comment (eight04) [inline picker/picker.css]: Can we use `:not(:first-child)` here?

File: picker/picker.html [hunk 3]
```diff
@@ -27,19 +27,23 @@
...
-			</label>
+			<div class="flex-stretch toolbar-control">
+				<label for="matchUrl">URL</label>
+				<div class="history-container flex-stretch">
+					<input type="text" id="matchUrl" placeholder="Regular expression" history="3">
+				</div>
+			</div>
 		</div>
-		<div class="flex-stretch">
+		<div>
```
Comment (eight04) [inline picker/picker.html]: Is this element needed?
